# Dockerfile
# Building Houston in production environment

FROM elixir:alpine as build
MAINTAINER Blake Kostner

RUN mkdir -p /app

COPY . /app
WORKDIR /app

ENV APP_NAME=houston_umbrella
ENV MIX_ENV=prod

RUN apk --no-cache --update add \
  git make g++ \
  nodejs nodejs-npm && \
  npm install npm -g --no-progress

RUN cd /app && \
  mix local.hex --force && \
  mix local.rebar --force && \
  mix deps.get && \
  mix deps.compile --all && \
  cd /app/apps/houston_dashboard/assets && \
  npm ci && \
  npx webpack --mode production && \
  cd /app/apps/houston_dashboard && \
  mix phx.digest && \
  cd /app && \
  mix release

RUN export RELEASE_DIR=`ls -d /app/_build/prod/rel/$APP_NAME/releases/*/` && \
  mkdir /export && \
  tar -xf "$RELEASE_DIR/$APP_NAME.tar.gz" -C /export && \
  mv /export/bin/$APP_NAME /export/bin/houston

# Dockerfile
# An OTP docker image for running production houston

FROM elixir:alpine as release
MAINTAINER Blake Kostner

RUN mkdir -p /opt/houston

COPY --from=build /export/ /opt/houston
WORKDIR /opt/houston

ENV MIX_APP=houston
ENV MIX_ENV=prod
ENV PORT=4000
ENV REPLACE_OS_VARS=true
ENV SHELL=/bin/bash

EXPOSE 4000

RUN apk add --no-cache bash openssl

ENTRYPOINT ["/opt/houston/bin/houston"]
CMD ["foreground"]
