# Dockerfile
# A dockerfile for Houston development

FROM elixir:alpine
MAINTAINER Blake Kostner

RUN mkdir -p /opt/houston

COPY . /opt/houston
WORKDIR /opt/houston

ENV APP_NAME=houston_umbrella

RUN apk --no-cache --update add \
  bash git make g++ inotify-tools \
  nodejs nodejs-npm && \
  npm install npm -g --no-progress

RUN cd /opt/houston && \
  mix local.hex --force && \
  mix local.rebar --force && \
  mix deps.get --all && \
  MIX_ENV=dev mix deps.compile --all && \
  MIX_ENV=test mix deps.compile --all && \
  cd /opt/houston/apps/houston_dashboard/assets && \
  npm ci

EXPOSE 4000

ENTRYPOINT ["mix"]
CMD ["phx.server"]
